export const SITE_TITLE = "Matt Ferderer"
export const SITE_DESCRIPTION = "Web Developer - Tinkering, Developing &amp; Engineering One Bit at a Time"
export const DOMAIN = "https://mattferderer.com"
export const TWITTER = "mattferderer"
export const STACKOVERFLOW = "mattferderer"
export const LINKEDIN = "mattferderer"
export const GITHUB = "mattferderer"
