export const SITE_TITLE: string
export const SITE_DESCRIPTION: string
export const DOMAIN: string
export const TWITTER: string
export const STACKOVERFLOW: string
export const LINKEDIN: string
export const GITHUB: string
export const AUTHOR: string
export const REPORTURI: string
export const DISQUS: string
export const BIO: string
export const AFFILIATE: string